from enum import Enum

class Team(Enum):
    ARI = "ARI"
    ATL = "ATL"
    BAL = "BAL"
    BOS = "BOS"
    CHN = "CHN"
    CHA = "CHA"
    CIN = "CIN"
    CLE = "CLE"
    COL = "COL"
    DET = "DET"
    HOU = "HOU"
    KCA = "KCA"
    ANA = "ANA"
    LAN = "LAN"
    MIA = "MIA"
    MIL = "MIL"
    MIN = "MIN"
    NYN = "NYN"
    NYA = "NYA"
    OAK = "OAK"
    PHI = "PHI"
    PIT = "PIT"
    SDN = "SDN"
    SEA = "SEA"
    SFN = "SFN"
    SLN = "SLN"
    TBA = "TBA"
    TEX = "TEX"
    TOR = "TOR"
    WAS = "WAS"

class Handedness(Enum):
    LEFT = "LEFT"
    RIGHT = "RIGHT"
    SWITCH = "SWITCH"

class Position(Enum):
    P = "P"
    C = "C"
    B1 = "1B"
    B2 = "2B"
    B3 = "3B"
    SS = "SS"
    LF = "LF"
    CF = "CF"
    RF = "RF"
    DH = "DH"
    UTIL = "UTIL"

